replicaCount: 1


image: grizzdominant/resume-site:4acaddc470af940f04b11a33d2255b683f67282b

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false  # Set to true if using Ingress
  host: resume.local

autoscaling:
  enabled: true  # Or true, depending on your needs
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
