replicaCount: 1


image: grizzdominant/resume-site:53cca3636d3087b9738fe3d6041960239c4d1970

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false  # Set to true if using Ingress
  host: resume.local

autoscaling:
  enabled: true  # Or true, depending on your needs
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
