apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
        - name: resume-site
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
