apiVersion: v1
kind: Service
metadata:
  name: resume-web-service
spec:
  selector:
    app: resume-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to "ClusterIP" if using an Ingress

