name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t grizzdominant/resume-site:latest .
          docker tag grizzdominant/resume-site:latest grizzdominant/resume-site:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push grizzdominant/resume-site:latest
          docker push grizzdominant/resume-site:${{ github.sha }}

      - name: Update Helm chart with new image tag
        run: |
          sed -i 's|image: grizzdominant/resume-site:.*|image: grizzdominant/resume-site:${{ github.sha }}|' helm-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add helm-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push

